Use bash

diff --git a/.github/workflows/manifest.yml b/.github/workflows/manifest.yml
--- a/.github/workflows/manifest.yml
+++ b/.github/workflows/manifest.yml
@@ -57,35 +57,32 @@ jobs:
           docker manifest push $IMAGE
 
       - name: Slack notification
-        shell: pwsh
         run: |
-          $headers = @{
-            "Authorization"="Bearer ${{ secrets.PAT_APPROVE_PR }}";
-            "Accept"="application/vnd.github+json";
-            "X-GitHub-Api-Version"="2022-11-28";
-            "Content-Type"="application/json"
-          }
-
-          #ref: https://docs.github.com/en/rest/repos/repos?apiVersion=2022-11-28#create-a-repository-dispatch-event
-          $apiRepoUrl = "https://api.github.com/repos/databox/deploy-config/dispatches"
+          HEADERS=(-H "Authorization: Bearer ${{ secrets.PAT_APPROVE_PR }}" \
+                  -H "Accept: application/vnd.github+json" \
+                  -H "X-GitHub-Api-Version: 2022-11-28" \
+                  -H "Content-Type: application/json")
           
-          $timestamp = [DateTimeOffset]::UtcNow.ToUnixTimeMilliseconds()
+          API_URL="https://api.github.com/repos/databox/deploy-config/dispatches"
           
-          $body = @{
-            event_type = "new_release_notification";
-            client_payload = @{
-              service_name = "${{ github.repository }}"
-              service_version = "${{ inputs.tag }}"
-              service_image = "${{ inputs.image }}"
-              service_repository = "${{ github.repository }}"
-              slack_channel = "C027FC31SVD"
+          PAYLOAD=$(cat <<EOF
+          {
+            "event_type": "new_release_notification",
+            "client_payload": {
+              "service_name": "${{ github.repository }}",
+              "service_version": "${{ inputs.tag }}",
+              "service_image": "${{ inputs.image }}",
+              "service_repository": "${{ github.repository }}",
+              "slack_channel": "C027FC31SVD"
             }
           }
-
-          $bodyString = $body | ConvertTo-Json
+          EOF
+          )
           
-          try {
-            Invoke-WebRequest -Uri "$apiRepoUrl" -Method Post -Headers $headers -Body $bodyString | Out-Null
-          } catch {
-            throw "$($_.exception[0].message)"
-          }  
+          if ! curl -s -f "${HEADERS[@]}" \
+                    -X POST \
+                    -d "$PAYLOAD" \
+                    "$API_URL"; then
+            echo "Failed to send notification"
+            exit 1
+          fi  
